### PR TITLE
Refactor: Move buildEli into its own class

### PR DESCRIPTION
**Pull request by hannes-mk**
Remove duplication

### CODE REVIEW

**Comment by hannes-mk** [comment]
How about builder() ?

**Comment by andreasphil** [comment]
As discussed: consider using a builder instead to avoid having such a long list of parameters. Just a suggestion though, looks good to me otherwise.

**Review by andreasphil — APPROVED** [review]

**Comment by malte-laukoetter** [comment]
> How about builder() ?

as the method name? if you want something other than the current one i would go with `build()`

Also I agree with Andreas that it looks good to me! and that using the builder-pattern might make the many parameters a bit simpler to use :)

**Review by malte-laukoetter — APPROVED** [review]

**Comment by reckseba** [comment]
Thanks for the invite. As the main goal was to remove duplication, I'd be okay with not refactoring it by using a builder pattern. The fact that we have more test coverage now, is already pretty nice.

**Review by reckseba — APPROVED** [review]
Thanks for the invite. As the main goal was to remove duplication, I'd be okay with not refactoring it by using a builder pattern. The fact that we have more test coverage now, is already pretty nice.

**Comment by hannes-mk** [comment]
@reckseba Thanks, Sebastian! Your answer made me pause and reconsider priorities. I have decided to not fine-tune this one, but focus on other tasks. Will merge.

**Pull request merged**
