### PR TITLE
Update backend libraries

### PR DESCRIPTION
**Pull request by hannes-mk**
- Fix format and sort using the gradle task "versionCatalogUpdate"

RISDEV-3431

### CODE REVIEW

**Comment by hannes-mk** [comment]
@VictorDelCampo This is what I get when running the gradle task "versionCatalogUpdate". I'd be interested if you think the generated TOML is fine.

**Comment by hannes-mk** [comment]
@VictorDelCampo And maybe we can handle those together? 
image

**Comment by VictorDelCampo** [comment]
@hannes-mk the generated TOML looks good! I see it is ordered alphabetically right? Why not... But i see the flyway-core is missing and the sl4fj? Please be aware the flyway-core is not going to be easy

**Comment by hannes-mk** [comment]
Done in https://github.com/digitalservicebund/ris-norms/commit/ebc0aac04800e8123a7346ec6a21c17ab73e71d0

**Pull request closed without merging**
