### PR TITLE
Remove build script

### PR DESCRIPTION
**Pull request by reckseba**
By simply moving the Docker build command to the Compose file, we could tidy up the project a little more. Do you agree?

### CODE REVIEW

**Comment by VictorDelCampo** [comment]
@reckseba it is a good idea although we would then be building the ris-norms image every time we run the docker compose right? And maybe you don't need to build the image again but rather just restart the services? 

Also documenting the docker-compose start-up is great and I would also do it in DEVELOPING.md but I would also add a sentence about the other way we have to start the application for local development (redis+postgres as containers but then using npm run dev and the gradle wrapper)

**Comment by reckseba** [comment]
@VictorDelCampo no that's not what happens. It will take the image from the local registry. Only on `docker compose build` you can force it to build. Though it will re-use cached layers which can be forced to re-create by adding `--no-cache` argument. The exact docu part can be found [here](https://docs.docker.com/compose/compose-file/build/#using-build-and-image).

For the second part: I can add that, too.

**Comment by VictorDelCampo** [comment]
Got it. Thanks for the explanation. Then yes!

**Review by VictorDelCampo — APPROVED** [review]

**Comment by hannes-mk** [comment]
:+1:  for getting rid of a "magic" shell script

**Pull request merged**
